### ISSUE TITLE
Poor performance

### ISSUE THREAD

**Issue by zhao-lun** [hcw-00/PatchCore_anomaly_detection#12]
Hi.

Thank you for providing this repository. 
So I was trying to reproduce the result obtained in the paper[Cable category]
Left[Input] / Middle[ Prediction] / Right [GT]
![image](https://user-images.githubusercontent.com/32569157/127624194-468ecb54-d45c-44e7-bebe-007612247023.png)

Note that, I have applied a 0.8 threshold on the anomaly map after the normalization.

```
anomaly_map_norm[anomaly_map_norm< 0.8] = 0
```
However, I noticed for the 'Good' samples. the result become weird. 

![image](https://user-images.githubusercontent.com/32569157/127624704-56b24dde-9408-44b7-802e-645fa499ebc7.png)

**Comment by hcw-00** [comment]
Hi. It is normal. Cause anomaly maps are minmax normalized before saving.
