### ISSUE TITLE
Using layer4

### ISSUE THREAD

**Issue by stvogel** [hcw-00/PatchCore_anomaly_detection#27]
Thanks for this great implementation.
In the paper the authors claim in "Evaluation on other benchmarks": 

> As the detection context is much closer to
> that of natural image data available in ImageNet and images
> are larger, we make use of deeper network feature maps at
> hierarchy levels 3 and 4, but otherwise do not perform any
> hyperparameter tuning for PatchCore.

I tried to simply swap layer2 and 3 to 3 and 4 and had to adapt the reshaping later on.
But the results were a complete failure. The heatmap is always blank.

Has someone tried to use layer4 successfully?

**Comment by royarahimzadeh** [comment]
I have tried layers 3,4 in the industrial version of this code :
(https://github.com/dhkdnduq/PatchCore_anomaly_detection)
like this:
self.model.layer3[-1].register_forward_hook(hook_t)
self.model.layer4[-1].register_forward_hook(hook_t)

For my input images, the results got lower auc_roc  than layer2,3.

**Comment by stvogel** [comment]
As this wasn't really an issue but a point of interest, I simply close it.
