### ISSUE TITLE
Possible error at final anomaly map

### ISSUE THREAD

**Issue by shakediel** [hcw-00/PatchCore_anomaly_detection#4]
hey there,
first of all thanks for the code!

regarding the final anomaly map computed:
shouldn't the finale rescaling of the scores be done to all patch features? and not only to the highest one?
thus creating a different anomaly map for the whole image?

any thoughts?
thanks!

**Comment by hcw-00** [comment]
Hi! Can you tell me which line? And please explain more.

**Comment by shakediel** [comment]
my bad, 
i missed the line where it said that s after scaling is the image level anomaly score.
