### ISSUE TITLE
save model problem "AttributeError: Can't pickle local object 'STPM.__init__.<locals>.hook_t'"

### ISSUE THREAD

**Issue by OppiHmiK** [hcw-00/PatchCore_anomaly_detection#5]
I'd like to save a model from training,  
when I used torch. save(model, 'save_model_path.pt'), The following error occurred
"AttributeError: Can't pickle local object 'STPM.__init__.<locals>.hook_t'
How can I save the model?

**Comment by hcw-00** [comment]
Hi. I think there is no need to save the model. The model itself is from torch hub. We just use pre-trained model and does not update weights.
