### ISSUE TITLE
Detection time is related to the training set size?

### ISSUE THREAD

**Issue by xfby2016** [hcw-00/PatchCore_anomaly_detection#8]
Hi,I find that the detection time grows longer as the training set grows,Is that reasonable?
The problem seems to related to this line of code,
https://github.com/hcw-00/PatchCore_anomaly_detection/blob/5680042fd114abbfbef820edef1f61d566a128fd/train.py#L280
Or is that a problem?Thanks

**Comment by hcw-00** [comment]
I think it is related to dataset size..

**Comment by xfby2016** [comment]
> I think it is related to dataset size..
Do you mean it is related to the number of pictures in the training set? 
So how much of dataset size is appropriate?

**Comment by hcw-00** [comment]
Yes, It is related to the number of pictures.
I don't know about that. But I think you should do some experiment and find your own conditions.

**Comment by xfby2016** [comment]
Okay, thanks, I'll try.
By the way,Is it reasonable to set the parameter N of the following code to a fixed value? Like the 50
https://github.com/hcw-00/PatchCore_anomaly_detection/blob/5680042fd114abbfbef820edef1f61d566a128fd/train.py#L280

**Comment by hcw-00** [comment]
I don't have deep insight about that. However, in my opinion, it depends on your dataset.
