### ISSUE TITLE
Trying to run the code with MVTec AD but: TypeError: 'NoneType' object is not iterable

### ISSUE THREAD

**Issue by andreluizbvs** [hcw-00/PatchCore_anomaly_detection#9]
I tried to run the code with the carpet class of the MVTec AD, but the above error was yielded.
I followed the installation process but, even so, this error appeared. Any idea why?

**Comment by hcw-00** [comment]
Can you check your dataset path is correctly given?

**Comment by andreluizbvs** [comment]
@hcw-00 Thank you for the quick answer!
I found out the problem: in the argument "--coreset_sampling_ratio 0.01", the 0.01 was being interpreted as a string object and not an integer.
